version: '3.8'

services:
  db:
    image: postgres:15
    container_name: weatherchecker-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: weatherchecker-app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${APP_HOST_PORT}:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
